from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

from harnessgym.artifacts import update_result
from harnessgym.config import RunConfig
from harnessgym.models import Artifact, IterationContext, RunnerResult
from harnessgym.registry import add_or_update_artifact, load_registry, save_registry

from .base import Runner


class FakeRunner(Runner):
    """Deterministic runner used by tests and offline demos."""

    def start_attempt(
        self,
        config: RunConfig,
        context: IterationContext,
        prompt: str,
    ) -> RunnerResult:
        started = time.monotonic()
        if context.iteration == 1:
            stdout = "Fake attempt 1 intentionally stops before solving and records missing tooling.\n"
            update_result(
                context.result_path,
                {
                    "status": "blocked",
                    "verified": False,
                    "summary": "Initial fake attempt blocked before completing the task.",
                    "blockers": ["Need a faster objective debugging/verifier loop."],
                    "missing_tooling": ["A reusable probe or verifier helper for the task."],
                },
            )
            status = "blocked"
        else:
            fixed = self._apply_known_demo_fix(context.workspace)
            verification = self._run_verifier_if_present(context.workspace)
            verified = verification["status"] == "passed"
            if not verified and not (context.workspace / "verifier.py").exists():
                verified = bool(context.registry.artifacts)
                verification = {"status": "passed", "command": "fake artifact-context check"}
            stdout = (
                "Fake fresh attempt received generated artifact context and used it.\n"
                f"demo_fix_applied={fixed}\n"
                f"verification_status={verification['status']}\n"
            )
            update_result(
                context.result_path,
                {
                    "status": "solved" if verified else "blocked",
                    "verified": verified,
                    "summary": "Fake fresh attempt used generated harness context.",
                    "verification": verification,
                    "used_artifacts": [artifact.to_dict() for artifact in context.registry.artifacts],
                },
            )
            status = "completed" if verified else "blocked"
        return self._record_phase(context, "attempt", prompt, stdout, "", started, status)

    def reflect(
        self,
        config: RunConfig,
        context: IterationContext,
        prompt: str,
        session_id: str | None,
    ) -> RunnerResult:
        started = time.monotonic()
        selected = {
            "kind": "tool",
            "name": "harnessgym_fake_probe",
            "reason": "Give the next fresh attempt a deterministic task probe and verifier entry point.",
            "target_path": ".harnessgym/tools/harnessgym_fake_probe.py",
        }
        update_result(
            context.result_path,
            {
                "reflection": {
                    "recommendations": [
                        "Add a reusable probe script that runs the task verifier and prints focused diagnostics.",
                        "Add a short task-specific skill summarizing the failure mode.",
                    ],
                    "selected_improvement": selected,
                }
            },
        )
        stdout = "Selected fake probe tool as the highest-leverage HarnessGym artifact.\n"
        return self._record_phase(context, "reflection", prompt, stdout, "", started, "completed", session_id)

    def build_tooling(
        self,
        config: RunConfig,
        context: IterationContext,
        prompt: str,
        session_id: str | None,
    ) -> RunnerResult:
        started = time.monotonic()
        tool_path = context.workspace / ".harnessgym" / "tools" / "harnessgym_fake_probe.py"
        tool_path.parent.mkdir(parents=True, exist_ok=True)
        tool_path.write_text(
            '''#!/usr/bin/env python3
"""Task probe generated by HarnessGym's deterministic fake runner."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def main() -> int:
    workspace = Path.cwd()
    verifier = workspace / "verifier.py"
    if not verifier.exists():
        print("No verifier.py found; probe can only confirm artifact availability.")
        return 0
    result = subprocess.run([sys.executable, str(verifier)], cwd=workspace, text=True)
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
''',
            encoding="utf-8",
        )
        registry = load_registry(context.workspace)
        artifact = Artifact(
            id="tool:.harnessgym/tools/harnessgym_fake_probe.py",
            kind="tool",
            path=".harnessgym/tools/harnessgym_fake_probe.py",
            description="Fake debugging probe that runs verifier.py when present.",
            iteration=context.iteration,
            metadata={"source": "fake-runner"},
        )
        add_or_update_artifact(registry, artifact)
        save_registry(context.workspace, registry)
        update_result(
            context.result_path,
            {
                "status": "tooling_built",
                "tooling": {
                    "built": [artifact.to_dict()],
                    "summary": "Created deterministic fake probe tool and updated registry.",
                },
            },
        )
        stdout = f"Created {tool_path}\nUpdated .harnessgym/registry.json\n"
        return self._record_phase(context, "build", prompt, stdout, "", started, "completed", session_id)

    def _record_phase(
        self,
        context: IterationContext,
        phase: str,
        prompt: str,
        stdout: str,
        stderr: str,
        started: float,
        status: str,
        session_id: str | None = None,
    ) -> RunnerResult:
        prompt_path = context.iteration_dir / f"{phase}.prompt.txt"
        stdout_path = context.iteration_dir / f"{phase}.stdout.txt"
        stderr_path = context.iteration_dir / f"{phase}.stderr.txt"
        transcript_path = context.iteration_dir / f"{phase}.transcript.txt"
        prompt_path.write_text(prompt, encoding="utf-8")
        stdout_path.write_text(stdout, encoding="utf-8")
        stderr_path.write_text(stderr, encoding="utf-8")
        effective_session = session_id or f"fake-session-{context.run_id}-{context.iteration}"
        duration = time.monotonic() - started
        transcript_path.write_text(
            "\n".join(
                [
                    "runner: fake",
                    f"phase: {phase}",
                    f"status: {status}",
                    f"duration_seconds: {duration:.3f}",
                    f"session_id: {effective_session}",
                    "",
                    stdout,
                ]
            ),
            encoding="utf-8",
        )
        return RunnerResult(
            phase=phase,
            status=status,
            session_id=effective_session,
            return_code=0,
            duration_seconds=duration,
            stdout_path=str(stdout_path),
            stderr_path=str(stderr_path),
            transcript_path=str(transcript_path),
            prompt_path=str(prompt_path),
        )

    def _apply_known_demo_fix(self, workspace: Path) -> bool:
        target = workspace / "kernel_ops.py"
        if not target.exists():
            return False
        text = target.read_text(encoding="utf-8")
        old = "norm = math.sqrt(sum(x * x for x in a)) + math.sqrt(sum(y * y for y in b))"
        new = "norm = math.sqrt(sum(x * x for x in a)) * math.sqrt(sum(y * y for y in b))"
        if old not in text:
            return False
        target.write_text(text.replace(old, new), encoding="utf-8")
        return True

    def _run_verifier_if_present(self, workspace: Path) -> dict:
        verifier = workspace / "verifier.py"
        if not verifier.exists():
            return {"status": "not_run", "command": "verifier.py not found"}
        command = [sys.executable, str(verifier)]
        result = subprocess.run(command, cwd=workspace, capture_output=True, text=True, timeout=10)
        return {
            "status": "passed" if result.returncode == 0 else "failed",
            "command": " ".join(command),
            "return_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }
